name: Pull Request

on:
  pull_request:
    branches:
    - master
    types: [opened, reopened, synchronize]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  Test:
    name: Test in ${{ matrix.testMode }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.2.1f1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Cache
        uses: actions/cache@v2
        with:
          path: /Library
          key: Library
          restore-keys: |
            Library
      - uses: game-ci/unity-test-runner@v2.0-alpha-2
        id: tests
        with:
          unityVersion: ${{ matrix.unityVersion }}
          customParameters: --unityLogName="/dev/stdout"
      - uses: actions/upload-artifact@v1
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}