name: Release

on:
  push:
    branches:
      - master

jobs:
  ReleaseUPM:
    name: Release to OpenUPM
    runs-on: ubuntu-18.04
    outputs:
      release: ${{ steps.semantic.outputs.new_release_published }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Versioning
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          git branch -d release &> /dev/null || echo release branch not found
          git subtree split -P Packages/CBSL -b release
          git push origin --all
      - name: Tagging
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo VERSION ${{ steps.semantic.outputs.new_release_version }}
          git tag upm/v${{ steps.semantic.outputs.new_release_version }} release
          git push origin --tags
  ReleaseDocs:
    name: Publish docs to Github Pages
    needs: ReleaseUPM
    if: needs.ReleaseUPM.outputs.release == 'true' || startsWith(github.event.head_commit.message, 'docs:')
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./Docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Enviornment Setup
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Build
        run: yarn build
      - name: Release
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Docs/build